#!/usr/bin/env bun
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dir, "..");
const outputPath = path.join(repoRoot, "src/generated/scaffold-assets.ts");
const assetRoots = ["static", "src/templates"] as const;

export type ScaffoldAssets = Record<string, string>;

function toPosixPath(filePath: string): string {
  return filePath.split(path.sep).join(path.posix.sep);
}

function isIgnoredAsset(name: string): boolean {
  return name === "__pycache__" || name.endsWith(".egg-info") || /\.(?:pyc|pyo)$/.test(name);
}

async function collectFiles(directoryPath: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(directoryPath, { withFileTypes: true });

  for (const entry of entries) {
    if (isIgnoredAsset(entry.name)) {
      continue;
    }

    const entryPath = path.join(directoryPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(entryPath)));
      continue;
    }

    if (entry.isFile()) {
      files.push(entryPath);
    }
  }

  return files;
}

export async function collectScaffoldAssets(root = repoRoot): Promise<ScaffoldAssets> {
  const assets: ScaffoldAssets = {};

  for (const assetRoot of assetRoots) {
    const files = await collectFiles(path.join(root, assetRoot));
    for (const file of files) {
      assets[toPosixPath(path.relative(root, file))] = await readFile(file, "utf8");
    }
  }

  return Object.fromEntries(Object.entries(assets).sort(([left], [right]) => left.localeCompare(right)));
}

export function formatScaffoldAssetsModule(assets: ScaffoldAssets): string {
  const lines = [
    "// Generated by scripts/generate-scaffold-assets.ts. Do not edit manually.",
    "export const scaffoldAssets: Record<string, string> = {",
  ];

  for (const [assetPath, content] of Object.entries(assets)) {
    lines.push(`  ${JSON.stringify(assetPath)}: ${JSON.stringify(content)},`);
  }

  lines.push("};", "");
  return lines.join("\n");
}

export async function writeScaffoldAssetsModule(root = repoRoot, destination = outputPath): Promise<void> {
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, formatScaffoldAssetsModule(await collectScaffoldAssets(root)), "utf8");
}

if (import.meta.main) {
  await writeScaffoldAssetsModule();
}
